## Welcome to ES/AM 158!

In [1]:
print("Hello World!")

Hello World!


# Common Libraries
* Numpy (Vector and Matrix operations, Numeric computing),
* Matplotlib (Plotting),
* Pandas/Polars (Table operations),
* Scikit-Learn (Machine Learning),
* PyTorch (Neural Networks),
* SymPy (Symbolic computations),


In [3]:
# (optinal) Install numpy if not already installed
!pip install numpy

In [6]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array A:\n", A)
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print("Array B:\n", B)
print("A + B:\n", A + B)

Array A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
A + B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
